### ISSUE TITLE
Upgrade select dependencies

### ISSUE THREAD

**Issue by BCerki** [button-inc/digital_marketplace#129]
### Description
As a developer
I want to use the latest versions of packages
So that my application can be more maintainable
### Tasks (How)
- [x] Update the dependencies that are **only outdated at the patch level** (see screenshot below for a list of what's included; red is old version, green is new)
- [x] Update the dependencies to the **next-highest minor version** (except knex, because this requires a major TS bump first, see screenshot below of what was included)
- [x] Update @commitlint/config-conventional mocha, and eslint-plugin-mocha to the latest versions
![Screenshot from 2022-01-14 09-50-06](https://user-images.githubusercontent.com/77306764/149561938-d9cec934-121b-4080-8f80-f09ff4d312ac.png)
![Screenshot from 2022-01-14 09-50-23](https://user-images.githubusercontent.com/77306764/149561950-96409fba-afc5-4e8f-9db5-441dde7ff069.png)
![Screenshot from 2022-01-14 09-50-34](https://user-images.githubusercontent.com/77306764/149561974-e0e3c426-b4f5-414c-a726-2fa5979cd925.png)

**Comment by BCerki** [comment]
Done in https://github.com/button-inc/digital_marketplace/pull/124
